### ISSUE TITLE
RealmTimelineAdapterのnotifyInsertedの処理が間違っている

### ISSUE THREAD

**Issue by akihito104** [akihito104/UdonRoad#19]

**Comment by akihito104** [comment]
06-06 12:03:12.555 13629-13629/com.freshdigitable.udonroad E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.freshdigitable.udonroad, PID: 13629
                                                                             java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1529151c position=24 id=-1, oldPos=5, pLpos:5 scrap [attachedScrap] tmpDetached no parent}
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4505)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4636)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
                                                                                 at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1482)
                                                                                 at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
                                                                                 at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:294)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:211)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by akihito104** [comment]
refs: d11449a
