### ISSUE TITLE
RTされたツイートが削除されると落ちる

### ISSUE THREAD

**Issue by akihito104** [akihito104/UdonRoad#43]
```
06-20 02:11:14.095 30877-30967/com.freshdigitable.udonroad D/UserStreamUtil: StatusDeletionNoticeImpl{statusId=744578107277905920, userId=42432969}
06-20 02:11:14.097 30877-30967/com.freshdigitable.udonroad D/UserStreamUtil: StatusDeletionNoticeImpl{statusId=744578159392088064, userId=42432969}
06-20 02:11:14.124 30877-30877/com.freshdigitable.udonroad D/RealmTimelineAdapter: call: deletedStatus
06-20 02:11:14.125 30877-30877/com.freshdigitable.udonroad D/RealmTimelineAdapter: call: deletedStatus
06-20 02:11:14.144 30877-30877/com.freshdigitable.udonroad D/REALM: Row 0x9f4217a0 is no longer attached!
06-20 02:11:14.144 30877-30877/com.freshdigitable.udonroad D/REALM: jni: ThrowingException 13, Object is no longer valid to operate on. Was it deleted by another thread?, .
06-20 02:11:14.145 30877-30877/com.freshdigitable.udonroad D/REALM: Exception has been throw: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?
06-20 02:11:14.145 30877-30877/com.freshdigitable.udonroad D/AndroidRuntime: Shutting down VM
06-20 02:11:14.148 30877-30877/com.freshdigitable.udonroad E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.freshdigitable.udonroad, PID: 30877
                                                                             java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                                 at io.realm.internal.UncheckedRow.nativeGetLong(Native Method)
                                                                                 at io.realm.internal.UncheckedRow.getLong(UncheckedRow.java:128)
                                                                                 at io.realm.StatusRealmRealmProxy.realmGet$id(StatusRealmRealmProxy.java:109)
                                                                                 at com.freshdigitable.udonroad.realmdata.StatusRealm.getId(StatusRealm.java:61)
                                                                                 at com.freshdigitable.udonroad.TimelineAdapter.getSelectedTweetId(TimelineAdapter.java:42)
                                                                                 at com.freshdigitable.udonroad.TimelineAdapter.onBindViewHolder(TimelineAdapter.java:84)
                                                                                 at com.freshdigitable.udonroad.TimelineAdapter.onBindViewHolder(TimelineAdapter.java:22)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:588)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3211)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3067)
                                                                                 at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1505)
                                                                                 at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:151)
                                                                                 at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:305)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:211)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by akihito104** [comment]
選択されていると落ちる

**Comment by akihito104** [comment]
選択されているかどうかは問題ではなかった。削除対象のretweetedStatusIdを持つデータを一緒に消してやることで解決。
